### ISSUE TITLE
For some categories we need new icons

### ISSUE THREAD

**Issue by bromix** [bromix/plugin.video.bromix.vimeo#7]
e.g. Groups or Albums

**Comment by freeman212** [comment]
how about this for groups:
![groups icon](https://raw.githubusercontent.com/freeman212/plugin.video.bromix.vimeo/1da34477cf121c146dc8a35c59da20b2fb58c364/resources/media/groups.png)
https://github.com/freeman212/plugin.video.bromix.vimeo/commit/1da34477cf121c146dc8a35c59da20b2fb58c364

**Comment by bromix** [comment]
Awesome! :)

**Comment by freeman212** [comment]
PR incoming ;-)

**Comment by bromix** [comment]
Okay...for the groups I merge #9 Thanks!

**Comment by bromix** [comment]
I think I have all the icons...channels is not so fitting...but this will work for now :)
